# Generated by Django 3.1.3 on 2021-05-06 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cooking time'),
        ),
    ]
