name: foodgram_workflow

on: [push]

jobs:         
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kofan1106/foodgram:latest

  deploy:
   runs-on: ubuntu-latest
   needs: build_and_push_to_docker_hub
   steps:
   - name: Check out the repo
     uses: actions/checkout@v2
   - name: Copy file via ssh password
     uses: appleboy/scp-action@master
     with:
       host: ${{ secrets.HOST }}
       username: ${{ secrets.USER }}
       key: ${{ secrets.SSH_KEY }}
       passphrase: ${{ secrets.PASSPHRASE }}
       port: 22
       source: 'docker-compose.yaml, nginx/nginx.conf, .env'
       target: '/home/${{ secrets.USER }}'
   - name: executing remote ssh commands to deploy
     uses: appleboy/ssh-action@master
     with:
       host: ${{ secrets.HOST }}
       username: ${{ secrets.USER }}
       key: ${{ secrets.SSH_KEY }}
       passphrase: ${{ secrets.PASSPHRASE }}
       script: |
         sudo docker pull kofan1106/foodgram:latest
         sudo docker-compose up -d
         sudo docker image prune -f
         sudo docker-compose run web python manage.py makemigrations
         sudo docker-compose run web python manage.py migrate

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!
